{{- $sel := dict "ctx" . "component" "frontend" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskboard.fullname" . }}-frontend
  labels:
    {{- include "taskboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "taskboard.selectorLabels" $sel | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "taskboard.selectorLabels" $sel | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend
          image: {{ include "taskboard.frontendImage" . | quote }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - {name: http, containerPort: {{ .Values.frontend.containerPort }}}
          readinessProbe:
            httpGet: {path: /, port: http}
            periodSeconds: 10
          livenessProbe:
            httpGet: {path: /healthz, port: http}
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          volumeMounts:
            - {name: tmp, mountPath: /tmp}
      volumes:
        - name: tmp
          emptyDir: {sizeLimit: 32Mi}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskboard.fullname" . }}-frontend
  labels:
    {{- include "taskboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    {{- include "taskboard.selectorLabels" $sel | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
