apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: production-webapp
spec:
  type: ClusterIP
  selector:
    app: web-app
  ports:
    - name: http
      port: 80
      targetPort: http
