#!/bin/bash
run() { echo "\$ $*"; eval "$@" 2>&1; local rc=$?; [ $rc -ne 0 ] && echo "[exit code: $rc]"; echo; }
rm -rf /root/cheatsheet; mkdir -p /root/cheatsheet; cd /root/cheatsheet
echo "===== A. NAVIGATION ====="
run "pwd"
run "mkdir -p project/src project/docs"
run "ls"
run "ls -l"
run "ls -la project"
run "tree project"
run "cd project/src && pwd && cd ../.. && pwd"
echo "===== B. CREATING / COPYING / MOVING / DELETING ====="
run "touch project/src/app.py project/src/utils.py project/docs/notes.md"
run "tree project"
run "cp project/src/app.py project/src/app_backup.py"
run "ls -1 project/src"
run "mv project/src/utils.py project/src/helpers.py"
run "ls -1 project/src"
run "rm project/src/app_backup.py"
run "ls -1 project/src"
run "mkdir emptydir && rmdir emptydir && echo 'rmdir removed the empty dir'"
echo "===== C. READING FILES ====="
run "printf 'alpha 10\nbravo 25\ncharlie 5\ndelta 25\necho 40\n' > data.txt"
run "cat data.txt"
run "cat -n data.txt"
run "head -2 data.txt"
run "tail -2 data.txt"
run "wc -l data.txt"
run "wc data.txt"
echo "===== D. SEARCHING AND FILTERING ====="
run "grep 'bravo' data.txt"
run "grep -n '25' data.txt"
run "grep -c '25' data.txt"
run "grep -i 'ALPHA' data.txt"
run "grep -v '25' data.txt"
run "find . -type f -name '*.py'"
run "find . -type d"
echo "===== E. TEXT PROCESSING ====="
run "sort data.txt"
run "sort -k2 -n data.txt"
run "cut -d' ' -f1 data.txt"
run "cut -d' ' -f2 data.txt | sort -n | uniq -c"
run "awk '{print \$1, \$2*2}' data.txt"
run "awk '{sum += \$2} END {print \"total =\", sum}' data.txt"
run "sed 's/bravo/BRAVO/' data.txt"
run "cat data.txt | tr 'a-z' 'A-Z'"
echo "===== F. PERMISSIONS AND OWNERSHIP ====="
run "echo '#!/bin/bash' > script.sh && echo 'echo hi' >> script.sh"
run "ls -l script.sh"
run "chmod +x script.sh"
run "ls -l script.sh"
run "./script.sh"
run "chmod 644 script.sh && ls -l script.sh"
run "chmod 755 script.sh && ls -l script.sh"
run "chown testuser:testuser data.txt && ls -l data.txt"
run "chown root:root data.txt && ls -l data.txt"
echo "===== G. PROCESSES ====="
run "ps"
run "ps aux | head -8"
run "ps -ef | head -6"
run "sleep 300 & echo \"started background sleep with PID \$!\""
run "ps aux | grep 'sleep 300' | grep -v grep"
run "pgrep -a sleep"
run "pkill -f 'sleep 300' && echo 'killed it'"
run "pgrep -a sleep; echo '(no output = process gone)'"
echo "===== H. DISK AND MEMORY ====="
run "df -h"
run "df -h / "
run "du -sh /root/cheatsheet"
run "du -h --max-depth=1 /root/cheatsheet"
run "free -h"
echo "===== I. SYSTEM INFO ====="
run "uname -a"
run "uname -r"
run "cat /etc/os-release"
run "uptime"
run "date"
run "date '+%Y-%m-%d %H:%M:%S'"
run "whoami"
run "id"
run "which ls grep awk"
echo "===== J. ARCHIVES AND COMPRESSION ====="
run "tar -czf project.tar.gz project"
run "ls -lh project.tar.gz"
run "tar -tzf project.tar.gz"
run "mkdir extracted && tar -xzf project.tar.gz -C extracted && tree extracted"
run "gzip -k data.txt && ls -lh data.txt data.txt.gz"
run "gunzip -f data.txt.gz && ls -lh data.txt"
echo "===== K. REDIRECTION AND PIPES ====="
run "echo 'written with >' > out.txt && cat out.txt"
run "echo 'appended with >>' >> out.txt && cat out.txt"
run "ls /nonexistent 2> err.txt; cat err.txt"
run "ls /root /nonexistent > both.txt 2>&1; cat both.txt"
run "cat data.txt | grep 25 | wc -l"
echo "===== L. SERVICES (systemd) ====="
run "systemctl is-active ssh nginx cron"
run "systemctl list-units --type=service --state=running --no-pager"
