#!/bin/bash
run() { echo "\$ $*"; eval "$@" 2>&1; local rc=$?; [ $rc -ne 0 ] && echo "[exit code: $rc]"; echo; }

echo "===== ENVIRONMENT ====="
run "cat /etc/os-release | head -3"
run "uname -a"
run "hostname"

echo "########## TASK 1: SOFT LINK & HARD LINK ##########"
rm -rf /root/linklab; mkdir -p /root/linklab; cd /root/linklab
run "echo 'This is the original file content.' > original.txt"
run "cat original.txt"
echo "---- create a SOFT link (symbolic link) ----"
run "ln -s original.txt soft.txt"
echo "---- create a HARD link ----"
run "ln original.txt hard.txt"
echo "---- inspect: -i shows the inode number, and column 2 is the link count ----"
run "ls -li"
run "stat -c '%n -> inode=%i links=%h size=%s type=%F' original.txt hard.txt soft.txt"
echo "---- both links read the same content ----"
run "cat soft.txt"
run "cat hard.txt"
echo "---- what does the soft link actually point at? ----"
run "readlink soft.txt"
run "file original.txt soft.txt hard.txt"
echo "---- write through the hard link, original changes too (same inode) ----"
run "echo 'appended via hard link' >> hard.txt"
run "cat original.txt"
echo "---- NOW DELETE THE ORIGINAL: this is the key difference ----"
run "rm original.txt"
run "ls -li"
echo "---- soft link is now DANGLING (broken) ----"
run "cat soft.txt"
echo "---- hard link still has all the data ----"
run "cat hard.txt"
run "stat -c '%n -> inode=%i links=%h' hard.txt"
echo "---- soft links CAN point at directories; hard links normally cannot ----"
run "mkdir mydir"
run "ln -s mydir dirlink"
run "ls -ld dirlink"
run "ln mydir dirhard"
echo "---- cleanup / deleting links ----"
run "rm soft.txt"
run "unlink dirlink"
run "ls -li"

echo "########## TASK 2: adduser vs useradd ##########"
run "which adduser useradd"
run "file /usr/sbin/adduser"
run "file /usr/sbin/useradd"
echo "---- useradd WITHOUT -m : no home directory is created ----"
run "useradd nohomeuser"
run "grep nohomeuser /etc/passwd"
run "ls -la /home"
run "id nohomeuser"
echo "---- useradd WITH -m : home directory created, but no password, default shell from /etc/default/useradd ----"
run "useradd -m -s /bin/bash useradduser"
run "grep useradduser /etc/passwd"
run "ls -la /home"
run "passwd -S useradduser"
echo "---- adduser : the friendly wrapper. Normally interactive; --disabled-password --gecos '' makes it scriptable ----"
run "adduser --disabled-password --gecos '' testuser"
run "grep testuser /etc/passwd"
run "ls -la /home"
run "ls -la /home/testuser"
run "id testuser"
run "passwd -S testuser"
run "groups testuser"
echo "---- side by side ----"
run "grep -E 'nohomeuser|useradduser|testuser' /etc/passwd"
run "ls -1 /home"
echo "---- deleting a test user ----"
run "deluser --remove-home nohomeuser"
run "ls -1 /home"

echo "########## TASK 3: journalctl ##########"
run "journalctl --version | head -2"
echo "---- how big is the journal / where does it live ----"
run "journalctl --disk-usage"
echo "---- view the most recent system logs ----"
run "journalctl -n 15 --no-pager"
echo "---- logs from this boot only ----"
run "journalctl -b --no-pager | head -20"
echo "---- LOGS FOR A SPECIFIC SERVICE using -u ----"
run "systemctl status ssh --no-pager | head -12"
run "journalctl -u ssh --no-pager"
echo "---- start nginx and then read only its logs ----"
run "systemctl start nginx"
run "systemctl is-active nginx"
run "journalctl -u nginx --no-pager"
echo "---- restart it and watch new entries appear for that unit ----"
run "systemctl restart nginx"
run "journalctl -u nginx --no-pager -n 10"
echo "---- filter by priority: errors and worse only ----"
run "journalctl -p err --no-pager | head -10"
echo "---- filter by time ----"
run "journalctl --since '10 minutes ago' --no-pager | head -10"
echo "---- follow mode (-f) streams live; shown with a timeout so it terminates here ----"
run "timeout 3 journalctl -u nginx -f --no-pager; echo '(stopped after 3s)'"
echo "---- list which units have logs ----"
run "journalctl --field _SYSTEMD_UNIT | head -10"
echo "---- json output, useful for tooling ----"
run "journalctl -u nginx -n 1 -o json-pretty --no-pager | head -20"
echo "---- kernel messages only ----"
run "journalctl -k --no-pager | head -5"
