#!/bin/bash
# ============================================================
#  System Information Script
#  Shell Scripting Homework
#  Name        : Sumit Akhuli
#  Enrollment  : 24bcs10158
#
#  Demonstrates: variables, echo, date, hostname, whoami, df,
#                ps, read -p, mkdir, touch, > output redirection
# ============================================================

# ---------- variables ----------
CURRENT_DATE=$(date)
HOST_NAME=$(hostname)
USER_NAME=$(whoami)
SCRIPT_NAME=$(basename "$0")

echo "==================================================="
echo "        SYSTEM INFORMATION REPORT"
echo "==================================================="
echo

# ---------- 1. current date ----------
echo "1. Current Date"
echo "---------------"
echo "Date : $CURRENT_DATE"
echo "Short: $(date '+%Y-%m-%d %H:%M:%S')"
echo

# ---------- 2. hostname ----------
echo "2. Hostname"
echo "-----------"
echo "Hostname : $HOST_NAME"
echo

# ---------- 3. username ----------
echo "3. Username"
echo "-----------"
echo "Logged in as : $USER_NAME"
echo "User details : $(id)"
echo

# ---------- 4. disk usage ----------
echo "4. Disk Usage"
echo "-------------"
df -h
echo

# ---------- 5. running processes ----------
echo "5. Running Processes (top 10)"
echo "-----------------------------"
ps aux | head -10
echo
TOTAL_PROCS=$(ps aux | tail -n +2 | wc -l)
echo "Total running processes : $TOTAL_PROCS"
echo

# ---------- 6. user input with read -p ----------
echo "6. User Input"
echo "-------------"
read -p "Enter a name for the report directory: " DIR_NAME
read -p "Enter a name for the report file: " FILE_NAME

# fall back to defaults if the user just pressed Enter
DIR_NAME=${DIR_NAME:-system_report}
FILE_NAME=${FILE_NAME:-processes.txt}

echo "You entered directory : $DIR_NAME"
echo "You entered file      : $FILE_NAME"
echo

# ---------- 7. create directory with mkdir ----------
echo "7. Creating Directory and File"
echo "------------------------------"
mkdir -p "$DIR_NAME"
echo "Created directory : $DIR_NAME"

# ---------- 8. create file with touch ----------
touch "$DIR_NAME/$FILE_NAME"
echo "Created file      : $DIR_NAME/$FILE_NAME"
echo

# ---------- 9. store process info in the file using > redirection ----------
echo "9. Writing Process Information to File"
echo "--------------------------------------"
REPORT_PATH="$DIR_NAME/$FILE_NAME"

# '>' overwrites / creates the file
echo "===== SYSTEM REPORT generated by $SCRIPT_NAME =====" > "$REPORT_PATH"

# '>>' appends the rest
{
  echo "Date     : $CURRENT_DATE"
  echo "Hostname : $HOST_NAME"
  echo "User     : $USER_NAME"
  echo
  echo "===== DISK USAGE ====="
  df -h
  echo
  echo "===== RUNNING PROCESSES ====="
  ps aux
} >> "$REPORT_PATH"

echo "Process information written to : $REPORT_PATH"
echo "File size : $(du -h "$REPORT_PATH" | cut -f1)"
echo "Line count: $(wc -l < "$REPORT_PATH") lines"
echo

echo "==================================================="
echo "        REPORT COMPLETE"
echo "==================================================="
