#!/bin/bash
run() { echo "\$ $*"; eval "$@" 2>&1; local rc=$?; [ $rc -ne 0 ] && echo "[exit code: $rc]"; echo; }
echo "########## 1. hostname ##########"
run "hostname"
run "hostname -f"
echo "########## 2. whoami ##########"
run "whoami"
run "id"
echo "########## 3. ip a ##########"
run "ip a"
echo "########## 4. hostname -I ##########"
run "hostname -I"
echo "########## 5. ip route ##########"
run "ip route"
run "ip route get 8.8.8.8"
echo "########## 6. ping ##########"
run "ping -c 4 8.8.8.8"
run "ping -c 3 google.com"
echo "########## 7. nslookup ##########"
run "nslookup google.com"
run "nslookup github.com"
echo "########## 8. curl ##########"
run "curl -I https://www.google.com"
run "curl -s https://api.github.com/zen"
run "curl -s -o /dev/null -w 'http_code=%{http_code} time_total=%{time_total}s size=%{size_download}bytes\n' https://www.google.com"
echo "########## 9. ss ##########"
run "ss -tuln"
run "ss -tp state listening"
echo "########## 10. /etc/hosts ##########"
run "cat /etc/hosts"
run "cat /etc/resolv.conf"
echo "---- add a custom entry and prove name resolution uses it ----"
run "echo '127.0.0.1   myapp.local' >> /etc/hosts"
run "cat /etc/hosts"
run "ping -c 2 myapp.local"
echo "########## 11. tracepath ##########"
run "tracepath -m 8 8.8.8.8"
echo "########## 12. traceroute ##########"
run "traceroute -m 8 8.8.8.8"
echo "########## 13. telnet ##########"
run "timeout 8 bash -c 'printf \"HEAD / HTTP/1.0\r\n\r\n\" | telnet www.google.com 80'"
run "timeout 5 telnet localhost 22"
